### ISSUE TITLE
Uncaught SyntaxError: Unexpected token !

### ISSUE THREAD

**Issue by gcfabri** [ga2mer/atom-lebab#13]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: elementary OS
**Thrown From**: [lebab](https://github.com/ga2mer/atom-lebab) package 0.10.0

### Stack Trace

Uncaught SyntaxError: Unexpected token !

```
At /home/gcfabri/.atom/packages/lebab/node_modules/espree/espree.js:443

SyntaxError: Unexpected token !
    at Parser.instance.raise.instance.raiseRecoverable (/packages/lebab/node_modules/espree/espree.js:439:19)
    at Parser.instance.unexpected (/packages/lebab/node_modules/espree/espree.js:472:14)
    at Parser.pp.jsx_parseIdentifier (/packages/lebab/node_modules/acorn-jsx/inject.js:191:12)
    at Parser.pp.jsx_parseNamespacedName (/packages/lebab/node_modules/acorn-jsx/inject.js:200:21)
    at Parser.pp.jsx_parseElementName (/packages/lebab/node_modules/acorn-jsx/inject.js:213:21)
    at Parser.pp.jsx_parseOpeningElementAt (/packages/lebab/node_modules/acorn-jsx/inject.js:287:22)
    at Parser.pp.jsx_parseElementAt (/packages/lebab/node_modules/acorn-jsx/inject.js:310:31)
    at Parser.pp.jsx_parseElement (/packages/lebab/node_modules/acorn-jsx/inject.js:359:17)
    at Parser.parseExprAtom (/packages/lebab/node_modules/acorn-jsx/inject.js:381:23)
    at /packages/lebab/node_modules/acorn/dist/acorn.js:1854:19)
    at /packages/lebab/node_modules/acorn/dist/acorn.js:1831:17)
    at /packages/lebab/node_modules/acorn/dist/acorn.js:1773:19)
    at /packages/lebab/node_modules/acorn/dist/acorn.js:1756:19)
    at /packages/lebab/node_modules/acorn/dist/acorn.js:1733:19)
    at /packages/lebab/node_modules/acorn/dist/acorn.js:1709:19)
    at /packages/lebab/node_modules/acorn/dist/acorn.js:767:45)
    at /packages/lebab/node_modules/acorn/dist/acorn.js:658:23)
    at Parser.parseTopLevel (/packages/lebab/node_modules/espree/espree.js:301:34)
    at Parser.parse (/packages/lebab/node_modules/acorn/dist/acorn.js:528:15)
    at Object.parse (/packages/lebab/node_modules/acorn/dist/acorn.js:3357:37)
    at Object.parse (/packages/lebab/node_modules/espree/espree.js:738:21)
    at Object.parse (/packages/lebab/node_modules/lebab/lib/Parser.js:27:29)
    at Object.parse (/packages/lebab/node_modules/recast/lib/parser.js:26:34)
    at /packages/lebab/node_modules/lebab/lib/Transformer.js:68:36
    at Transformer.ignoringHashBangComment (/packages/lebab/node_modules/lebab/lib/Transformer.js:95:25)
    at Transformer.applyAllTransforms (/packages/lebab/node_modules/lebab/lib/Transformer.js:67:19)
    at Transformer.run (/packages/lebab/node_modules/lebab/lib/Transformer.js:58:20)
    at Object.exports.transform (/packages/lebab/node_modules/lebab/index.js:14:62)
    at Converter.convert (/packages/lebab/lib/Converter.js:13:40)
    at Object.convert (/packages/lebab/lib/lebab.js:30:40)
    at /packages/lebab/lib/lebab.js:16:24)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -1:53 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-base16-tomorrow-dark-theme.theme-one-dark-ui)
     -1:21.6.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-base16-tomorrow-dark-theme.theme-one-dark-ui)
     -0:26 lebab:convert (input.hidden-input)
```

### Non-Core Packages

```
angular-2-typeScript-snippets 0.6.3 
angularjs 0.4.0 
atom-beautify 0.29.17 
atom-typescript 10.1.14 
autoclose-html 0.23.0 
emmet 2.4.3 
file-icons 2.0.17 
foldingtext-for-atom 0.9.2 
git-plus 7.3.3 
highlight-selected 0.12.0 
keyboard-sounds 0.2.0 
lebab 0.10.0 
linter 1.11.23 
linter-bootlint 1.0.4 
linter-csslint 1.3.4 
linter-htmlhint 1.3.2 
linter-jshint 3.0.3 
linter-jsonlint 1.3.0 
linter-php 1.3.1 
linter-sass-lint 1.7.4 
linter-scss-lint 3.1.0 
linter-tslint 0.14.0 
markdown-writer 2.6.4 
minimap 4.26.8 
minimap-highlight-selected 4.5.0 
minimap-pigments 0.2.2 
pigments 0.39.0 
svg-preview 0.11.0 
todo-show 1.11.0 
typewriter-sounds 0.1.0 
```

**Comment by nene** [comment]
Hard to say what's going on without any details on how to reproduce it.

My guess is that I see several TypeScript packages installed, and there's parse error happening. So perhaps you're trying to run it on TypeScript, which isn't necessarily valid JavaScript and getting errors.

Another guess is that atom-lebab allows you to select a portion of code and only transform that, but the portion of code you select might not make up a valid chunk of JavaScript in itself.
